export const defaultAccountInfo = {
  fullName: "",
  avatarUrl: "",
  address: "",
  campusId: 0,
  dateOfBirth: "",
  major: "",
  currentTermNo: 0,
  dateOfIssue: "",
  email: "",
  enrollDate: "",
  firstName: "",
  lastName: "",
  gender: true,
  homePhone: "",
  idCard: "",
  studentCode: "",
  parentName: "",
  parentPhone: "",
  parentJob: "",
  parentEmail: "",
  parentAddress: "",
  placeOfIssue: "",
  placeOfWork: "",
  progress: false,
  rollNumber: "",
  statusCode: "",
}
